# Generated by Django 2.2.24 on 2021-12-16 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_genre',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('hip-hop-rap', 'Hip-hop and Rap'), ('rock', 'Rock'), ('dance-and-electric-music', 'Dance and Electronic music'), ('jazz', 'Jazz'), ('funk', 'Funk'), ('classical-music', 'Classical Music'), ('k-pop', 'K-Pop'), ('opera', 'Opera'), ('metal', 'Metal'), ('others', 'Others')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=55, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
