# Generated by Django 2.2.24 on 2021-12-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='PasswordResetToken',
        ),
    ]
