# Generated by Django 2.2.24 on 2021-12-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211216_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/images/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_id', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
