# Generated by Django 2.2.25 on 2022-01-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_assetstransaction_profile_questionanswer_requestpop_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
